name: fruite_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dots_indicator: ^4.0.1
  equatable: ^2.0.7
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  google_sign_in: ^6.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_facebook_auth: ^7.1.2
  flutter_localizations:
    sdk: flutter
  get_it: ^9.2.0
  intl: ^0.20.2
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences: ^2.5.3
  svg_flutter: ^0.0.1
  cloud_firestore: ^6.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: "Cairo"
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils
  filename: app_images.dart
  field_prefix: null
flutter_intl:
  enabled: true
